### ISSUE TITLE
Error: filter not found (sometimes happens, others not) - Running Python on Windows (Anaconda)

### ISSUE THREAD

**Issue by 666birdman** [CodeWithJoe2020/pythonSniperbot#1]
Traceback (most recent call last):
  File "sniperBot.py", line 125, in <module>
    main()
  File "sniperBot.py", line 116, in main    
    log_loop(event_filter,2 )))
  File "C:\Users\XXXXX\Anaconda3\lib\asyncio\base_events.py", line 488, in run_until_complete
    return future.result()
  File "sniperBot.py", line 99, in log_loop
    for PairCreated in event_filter.get_new_entries():
  File "C:\Users\XXXXX\Anaconda3\lib\site-packages\web3\_utils\filters.py", line 160, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "C:\Users\XXXXX\Anaconda3\lib\site-packages\web3\module.py", line 60, in caller
    null_result_formatters)
  File "C:\Users\XXXXX\Anaconda3\lib\site-packages\web3\manager.py", line 184, in request_blocking
    null_result_formatters)
  File "C:\Users\XXXXX\Anaconda3\lib\site-packages\web3\manager.py", line 162, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'filter not found'}

**Comment by hoangduyloc** [comment]
@666birdman same problem, I tried to reinstall the web3 lib, but also meet the same problems. Did u figure it out?

**Comment by marcolole** [comment]
Same, sometimes it happens in 1 minute, sometime in 5 minutes, but I can’t fix this issue, someone has solved this issue?

**Comment by hoangduyloc** [comment]
try:
  doing st
expect:
  error
Will get rid of it.

**Comment by 666birdman** [comment]
> 
> 
> try:
> doing st
> expect:
> error
> Will get rid of it.

Does the filter stay activated? Don't you still miss some of the pairs?
