### ISSUE TITLE
Web3.Exception.ABIEventFunctionNotFound

### ISSUE THREAD

**Issue by sjbruni** [CodeWithJoe2020/pythonSniperbot#5]
Hello Joe! Great script!!!
I'm having troubles when tried to use pancakeswap instead Uniswap.
with Pancakeswap, I'm getting the error:
```
Traceback (most recent call last):
  File "c:\Users\H\OneDrive\Scripts\python\Garbage_Tests\code_w_Joe_sniping_v1.py", line 116, in <module>
    main()
  File "c:\Users\H\OneDrive\Scripts\python\Garbage_Tests\code_w_Joe_sniping_v1.py", line 102, in main
    event_filter = contractbuy.events.PairCreated.createFilter(fromBlock='latest')
  File "C:\Users\H\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\contract.py", line 254, 
in __getattr__
    raise ABIEventFunctionNotFound(
web3.exceptions.ABIEventFunctionNotFound: ("The event 'PairCreated' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')
```
I see you are using "contract" for uniswap and "contractbuy" for pancakeswap:
contract = web3.eth.contract(address=uniswap_factory, abi=uniswap_factory_abi)
contractbuy = web3.eth.contract(address=panRouterContractAddress, abi=panabi)

There is an issue with the ABI contract in PancakeSwap, that really doent have paircreated event?

**Comment by sjbruni** [comment]
I got the issue. I just confused the Router vs Factory Contract...
